version: 2
updates:
  # - package-ecosystem: "devcontainers"
  #   directory: "/"
  #   schedule:
  #     interval: monthly

  # - package-ecosystem: "docker"
  #   directory: "/"
  #   schedule:
  #     interval: monthly

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "next"
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "tailwindcss"
      - dependency-name: "@tailwindcss/forms"
      - dependency-name: "@tailwindcss/typography"
      - dependency-name: "@tailwindcss/aspect-ratio"
      - dependency-name: "autoprefixer"
      - dependency-name: "postcss"
