#!/usr/bin/env bash
set -euo pipefail

# ── Config ──────────────────────────────────────────
# If you’d like a different region, export AWS_REGION before running
REGION="${AWS_REGION:-ap-southeast-1}"
# Where your .tf files live
TF_DIR="terraform"
TF_VARS_FILE="$TF_DIR/terraform.tfvars"

# ── Generate a unique key pair name ─────────────────
KEY_NAME="tf-key-$(date +%Y%m%d%H%M%S)"

echo "➤ Creating EC2 Key Pair: $KEY_NAME (region: $REGION)"
aws ec2 create-key-pair \
  --region "$REGION" \
  --key-name "$KEY_NAME" \
  --query 'KeyMaterial' \
  --output text > "${KEY_NAME}.pem"
chmod 400 "${KEY_NAME}.pem"
echo "  → Saved private key to $(pwd)/${KEY_NAME}.pem"

# ── Lookup default VPC ─────────────────────────────
echo "➤ Retrieving default VPC ID in region $REGION"
VPC_ID=$(aws ec2 describe-vpcs \
  --region "$REGION" \
  --filters Name=isDefault,Values=true \
  --query 'Vpcs[0].VpcId' \
  --output text)

if [[ -z "$VPC_ID" ]]; then
  echo "✖ Could not find a default VPC in $REGION"
  exit 1
fi
echo "  → Default VPC ID: $VPC_ID"

# ── Emit terraform.tfvars ──────────────────────────
echo "➤ Writing Terraform variables to $TF_VARS_FILE"
mkdir -p "$TF_DIR"
cat > "$TF_VARS_FILE" <<EOF
# Auto-generated by setup_terraform_env.sh
key_pair_name = "$KEY_NAME"
vpc_id        = "$VPC_ID"
EOF

echo "✔ All done! You can now:"
echo "    cd $TF_DIR"
echo "    terraform init"
echo "    terraform plan"