#!/usr/bin/env sh

echo ""
echo "🔍 Memvalidasi pesan commit menggunakan commitlint..."

# Simpan error output commitlint ke variabel
ERROR_MSG=$(npx --no-install commitlint --edit "$1" 2>&1)
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
  echo ""
  echo "❌ Pesan commit tidak valid menurut aturan commitlint! Commit dibatalkan."
  echo ""
  echo "Detail error:"
  echo "$ERROR_MSG"
  echo ""
  exit 1
fi

echo ""
echo "✅ Pesan commit valid."
echo ""
