#!/usr/bin/env sh

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

echo "🔄 Memeriksa dan menginstall dependency setelah merge..."

npm install
if [ $? -ne 0 ]; then
  echo "${RED}❌ Gagal install dependencies!${NC}"
  exit 1
fi

echo "${GREEN}✅ Dependencies berhasil diinstall.${NC}"