#!/usr/bin/env sh

echo ""
echo "🔄 Memeriksa dan menginstall dependency setelah merge..."

# Simpan output error npm install ke variabel
ERROR_MSG=$(npm install 2>&1)
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
  echo ""
  echo "❌ Gagal install dependencies!"
  echo ""
  echo "Detail error:"
  echo "$ERROR_MSG"
  echo ""
  exit 1
fi
echo ""
echo "✅ Dependencies berhasil diinstall."
echo ""
